Traceback (most recent call last):
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

# „Éô„ÇØ„Éà„É´ÊºîÁÆó„ÇíË°å„ÅÜ
result_vector = model.wv['king'] - model.wv['man'] + model.wv['woman']

# È°û‰ººÂ∫¶„ÅÆÈ´ò„ÅÑ10Ë™û„ÇíÂèñÂæó
similar_words = model.wv.most_similar(positive=[result_vector], topn=10)

# ÁµêÊûú„ÇíÂá∫Âäõ
for word, similarity in similar_words:
    print(f"{word}: {similarity:.4f}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[8], line 2[0m
[1;32m      1[0m [38;5;66;03m# „Éô„ÇØ„Éà„É´ÊºîÁÆó„ÇíË°å„ÅÜ[39;00m
[0;32m----> 2[0m result_vector [38;5;241m=[39m [43mmodel[49m[38;5;241;43m.[39;49m[43mwv[49m[[38;5;124m'[39m[38;5;124mking[39m[38;5;124m'[39m] [38;5;241m-[39m model[38;5;241m.[39mwv[[38;5;124m'[39m[38;5;124mman[39m[38;5;124m'[39m] [38;5;241m+[39m model[38;5;241m.[39mwv[[38;5;124m'[39m[38;5;124mwoman[39m[38;5;124m'[39m]
[1;32m      4[0m [38;5;66;03m# È°û‰ººÂ∫¶„ÅÆÈ´ò„ÅÑ10Ë™û„ÇíÂèñÂæó[39;00m
[1;32m      5[0m similar_words [38;5;241m=[39m model[38;5;241m.[39mwv[38;5;241m.[39mmost_similar(positive[38;5;241m=[39m[result_vector], topn[38;5;241m=[39m[38;5;241m10[39m)

[0;31mAttributeError[0m: 'KeyedVectors' object has no attribute 'wv'

